### ISSUE TITLE
Update pip command with pip3

### ISSUE THREAD

**Issue by fdicarlo** [zilexa/autosetup#1]
As python3-pip is installed by this script the command should be pip3 rather than pip, this is the output from my installation:

```
osmc@osmc:~$ pip install
-bash: pip: command not found
osmc@osmc:~$ pip3 install
You must give at least one requirement to install (see "pip help install")
osmc@osmc:~$ sudo pip
sudo: pip: command not found
osmc@osmc:~$
```

**Comment by zilexa** [comment]
Check, you are right. I made the changes but won't have a test system until next week.
